# Generated by Django 4.2.6 on 2023-10-11 15:07

from django.db import migrations
from guard.models import User, SafeguardLead, Therapist, Client, Appointment
from datetime import datetime


mock_data = {
    'SafeguardLead': [
        {
            'name': 'Bill West'
        }
    ],
    'Therapist': [
        {
            'name': 'John Smith',
            'safeguard_lead': 'Bill West'
        },
        {
            'name': 'Peter Pan',
            'safeguard_lead': 'Bill West'
        },
        {
            'name': 'Sloan Hunter',
            'safeguard_lead': 'Bill West'
        }
    ],
    'Client': [
        {
            'name': 'Toby Day',
            'age': 10,
        },
        {
            'name': 'Crew Cisneros',
            'age': 17,
        },
        {
            'name': 'Emerald Lloyd',
            'age': 25
        },
        {
            'name': 'Alani Booth',
            'age': 61
        }
    ],
    'Appointment': [
        {
            'therapist': 'John Smith',
            'client': 'Emerald Lloyd',
            'start_time': datetime(year=2023, month=10, day=12, hour=13, minute=0),
            'end_time': datetime(year=2023, month=10, day=12, hour=13, minute=30),
            'app_type': 'Virtual',
        },
        {
            'therapist': 'John Smith',
            'client': 'Crew Cisneros',
            'start_time': datetime(year=2023, month=10, day=12, hour=14, minute=0),
            'end_time': datetime(year=2023, month=10, day=12, hour=15, minute=00),
            'app_type': 'Virtual',
        },
        {
            'therapist': 'John Smith',
            'client': 'Toby Day',
            'start_time': datetime(year=2023, month=10, day=12, hour=9, minute=0),
            'end_time': datetime(year=2023, month=10, day=12, hour=9, minute=45),
            'app_type': 'Home',
        }
    ]
}


def clean_name(name):
    return name.lower().replace(' ', '_')


def create_users(*args, **kwargs):
    for user in mock_data['SafeguardLead']:
        u = SafeguardLead(
            name=user['name'],
            )
        u.save()
    for user in mock_data['Therapist']:
        u = Therapist(
            name=user['name'], 
            email=f"{clean_name(user['name'])}@listeningear.com",
            phone="+44123456789",
            safeguard_lead=SafeguardLead.objects.get(name=user['safeguard_lead'])
        )
        u.save()
    for user in mock_data['Client']:
        u = Client(
            name=user['name'],
            email=f"{clean_name(user['name'])}@hotmail.com",
            age=user['age'],
        )
        u.save()

    for app in mock_data['Appointment']:
        a = Appointment(
            therapist=Therapist.objects.get(name=app['therapist']),
            client=Client.objects.get(name=app['client']),
            start_time=app['start_time'],
            end_time=app['end_time'],
            app_type=app['app_type']
        )
        a.save()


class Migration(migrations.Migration):

    dependencies = [
        ('guard', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_users),
    ]
