# Generated by Django 4.2.6 on 2023-10-11 15:07

from django.db import migrations
from guard.models import User, SafeguardLead, Therapist, Client, Appointment
from datetime import datetime


mock_data = {
    'SafeguardLead': [
        {
            'name': 'Bill West'
        },
                {
            'name': 'Jack Ryan'
        }
    ],
    'Therapist': [
        {
            'name': 'John Smith',
            'safeguard_lead': 'Bill West',
            'url': 'https://unsplash.com/photos/7YVZYZeITc8',
        },
        {
            'name': 'Peter Pan',
            'safeguard_lead': 'Bill West'
        },
        {
            'name': 'Sloan Hunter',
            'safeguard_lead': 'Bill West'
        },
        {
            'name': 'Mathew Patton',
            'safeguard_lead': 'Bill West'
        },
        {
            'name': 'Lorelei Norman',
            'safeguard_lead': 'Bill West'
        },
        {
            'name': 'Aziel Durham',
            'safeguard_lead': 'Bill West'
        },
        {
            'name': 'Tiffany Mueller',
            'safeguard_lead': 'Bill West'
        },
        {
            'name': 'Albert Berry',
            'safeguard_lead': 'Bill West'
        },
        {
            'name': 'Annabelle Copeland',
            'safeguard_lead': 'Bill West'
        },
        {
            'name': 'Axton Velasquez',
            'safeguard_lead': 'Bill West'
        },
        {
            'name': 'Esme McClain',
            'safeguard_lead': 'Jack Ryan'
        },
        {
            'name': 'Mitchell Sims',
            'safeguard_lead': 'Jack Ryan'
        },
        {
            'name': 'Lena Dalton',
            'safeguard_lead': 'Jack Ryan'
        },
        {
            'name': 'Fletcher Fischer',
            'safeguard_lead': 'Jack Ryan'
        },
        {
            'name': 'Maci Conley',
            'safeguard_lead': 'Jack Ryan'
        },
        {
            'name': 'Marvin White',
            'safeguard_lead': 'Jack Ryan'
        },
        {
            'name': 'Layla Wise',
            'safeguard_lead': 'Jack Ryan'
        },
        {
            'name': 'Frederick Rollins',
            'safeguard_lead': 'Jack Ryan'
        },
        {
            'name': 'Araceli Lucas',
            'safeguard_lead': 'Jack Ryan'
        },
        {
            'name': 'Chance Martinez',
            'safeguard_lead': 'Jack Ryan'
        }     
    ],
    'Client': [
        {
            'name': 'Toby Day',
            'age': 10,
        },
        {
            'name': 'Crew Cisneros',
            'age': 17,
        },
        {
            'name': 'Emerald Lloyd',
            'age': 25
        },
        {
            'name': 'Harper Mills',
            'age': 45
        },
        {
            'name': 'Alex Mendez',
            'age': 33
        },
        {
            'name': 'Londyn Rivers',
            'age': 24
        },
        {
            'name': 'Bear Peralta',
            'age': 39
        },
        {
            'name': 'Malayah Hodges',
            'age': 40
        },
        {
            'name': 'Alonzo Travis',
            'age': 16
        },
        {
            'name': 'Mazikee Walter',
            'age': 21
        },
        {
            'name': 'Lochlan Tang',
            'age': 30
        },
        {
            'name': 'Belle Jennings',
            'age': 40
        },
        {
            'name': 'Corbin Young',
            'age': 43
        },
        {
            'name': 'Zoey Schneider',
            'age': 27
        },
        {
            'name': 'Raymond Novak',
            'age': 61
        },
        {
            'name': 'Kaiya Beil',
            'age': 51
        },
        {
            'name': 'Ariel Fuller',
            'age': 36
        },
        {
            'name': 'Oakley Bean',
            'age': 21
        },
        {
            'name': 'Mccoy Bass',
            'age': 37
        },
        {
            'name': 'Zahra O\'brien',
            'age': 22
        },
        {
            'name': 'Riley Salgado',
            'age': 53
        },
        {
            'name': 'Avalynn Daniels',
            'age': 31
        },
        {
            'name': 'Xander Fowler',
            'age': 33
        },
        {
            'name': 'Lennon Ortega',
            'age': 60
        },
        {
            'name': 'Kobe Welch',
            'age': 36
        },
        {
            'name': 'Amira McBride',
            'age': 15
        },
        {
            'name': 'Denver Charles',
            'age': 28
        },
        {
            'name': 'Jenna Orr',
            'age': 42
        },
        {
            'name': 'Benicio Flowers',
            'age': 35
        },
        {
            'name': 'Ariya Lim',
            'age': 31
        },
        {
            'name': 'Cal Richard',
            'age': 32
        },
        {
            'name': 'Davina Cox',
            'age': 33
        },
        {
            'name': 'Connor Stephens',
            'age': 34
        },
        {
            'name': 'Millie Saunders',
            'age': 35
        },
        {
            'name': 'Kasen Knapp',
            'age': 36
        },
        {
            'name': 'Linda Evans',
            'age': 37
        },
        {
            'name': 'Elias Washington',
            'age': 38
        },
        {
            'name': 'Wilder Shepherd',
            'age': 39
        },
        {
            'name': 'Valerie Rosales',
            'age': 40
        },
        {
            'name': 'Katalina Mays',
            'age': 41
        },
        {
            'name': 'Jadiel Russo',
            'age': 42
        },
        {
            'name': 'Tinsley Velez',
            'age': 43
        },
        {
            'name': 'Kareem Humphrey',
            'age': 44
        },
        {
            'name': 'Journi Burke',
            'age': 45
        },
        {
            'name': 'Jax Marks',
            'age': 46
        },
        {
            'name': 'Monica Gordon',
            'age': 47
        },
        {
            'name': 'Karter Beil',
            'age': 48
        },
        {
            'name': 'Itzel Mueller',
            'age': 49
        },
        {
            'name': 'Albert McDowell',
            'age': 50
        },
        {
            'name': 'Rayna Liu',
            'age': 51
        },
        {
            'name': 'Pedro Hernandez',
            'age': 52
        },
        {
            'name': 'Camila Pollard',
            'age': 53
        },
        {
            'name': 'Jad Austin',
            'age': 54
        },
        {
            'name': 'Alivia Watts',
            'age': 55
        },
        {
            'name': 'Dakota Goodman',
            'age': 56
        },
        {
            'name': 'Carolina Brady',
            'age': 57
        },
        {
            'name': 'Reed Quintero',
            'age': 58
        },
        {
            'name': 'Keyla Morrison',
            'age': 59
        },
        {
            'name': 'Maximus Bautista',
            'age': 60
        },
        {
            'name': 'Antonella Ali',
            'age': 61
        },
        {
            'name': 'Arjun Franco',
            'age': 62
        },
        {
            'name': 'Charleigh Bradshaw',
            'age': 63
        },
        {
            'name': 'Emory Thomas',
            'age': 64
        },
        {
            'name': 'Elizabeth Pearson',
            'age': 65
        },
        {
            'name': 'Gunner Powell',
            'age': 66
        },
        {
            'name': 'Vivian Cervantes',
            'age': 67
        },
        {
            'name': 'Kamari Santana',
            'age': 68
        },
        {
            'name': 'Myra Rowe',
            'age': 69
        },
        {
            'name': 'Kamden Fischer',
            'age': 70
        },
        {
            'name': 'Maci Lee',
            'age': 71
        },
        {
            'name': 'Jack Walters',
            'age': 72
        },
        {
            'name': 'Samara Jefferson',
            'age': 73
        }
    ],
    'Appointment': [
        {
            'therapist': 'John Smith',
            'client': 'Emerald Lloyd',
            'start_time': datetime(year=2023, month=10, day=12, hour=13, minute=0),
            'end_time': datetime(year=2023, month=10, day=12, hour=13, minute=30),
            'app_type': 'Virtual',
        },
        {
            'therapist': 'John Smith',
            'client': 'Crew Cisneros',
            'start_time': datetime(year=2023, month=10, day=12, hour=14, minute=0),
            'end_time': datetime(year=2023, month=10, day=12, hour=15, minute=00),
            'app_type': 'Virtual',
        },
        {
            'therapist': 'John Smith',
            'client': 'Toby Day',
            'start_time': datetime(year=2023, month=10, day=12, hour=9, minute=0),
            'end_time': datetime(year=2023, month=10, day=12, hour=9, minute=45),
            'app_type': 'Home',
        }
    ]
}


def clean_name(name):
    return name.lower().replace(' ', '_')


def create_users(*args, **kwargs):
    for user in mock_data['SafeguardLead']:
        u = SafeguardLead(
            name=user['name'],
            )
        u.save()
    for user in mock_data['Therapist']:
        u = Therapist(
            name=user['name'], 
            email=f"{clean_name(user['name'])}@listeningear.com",
            phone="+44123456789",
            safeguard_lead=SafeguardLead.objects.get(name=user['safeguard_lead'])
        )
        u.save()
    for user in mock_data['Client']:
        u = Client(
            name=user['name'],
            email=f"{clean_name(user['name'])}@hotmail.com",
            age=user['age'],
        )
        u.save()

    for app in mock_data['Appointment']:
        a = Appointment(
            therapist=Therapist.objects.get(name=app['therapist']),
            client=Client.objects.get(name=app['client']),
            start_time=app['start_time'],
            end_time=app['end_time'],
            app_type=app['app_type']
        )
        a.save()


class Migration(migrations.Migration):

    dependencies = [
        ('guard', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_users),
    ]
