# Generated by Django 4.2.6 on 2023-10-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guard', '0002_auto_20231011_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='check_in_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='check_out_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='checked_in',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='checked_out',
            field=models.BooleanField(null=True),
        ),
    ]
