# Generated by Django 4.2.6 on 2023-10-12 09:53

# Generated by Django 4.2.6 on 2023-10-11 15:07

from django.db import migrations
from guard.models import User, SafeguardLead, Therapist, Client, Appointment
from datetime import datetime


mock_data = {
    'Appointment': [
        {
            'therapist': 'Peter Pan',
            'client': 'Harper Mills',
            'start_time': datetime(year=2023, month=10, day=12, hour=9, minute=0),
            'end_time': datetime(year=2023, month=10, day=12, hour=9, minute=45),
            'app_type': 'Virtual',
        },
        {
            'therapist': 'Peter Pan',
            'client': 'Alex Mendez',
            'start_time': datetime(year=2023, month=10, day=12, hour=10, minute=0),
            'end_time': datetime(year=2023, month=10, day=12, hour=10, minute=45),
            'app_type': 'Virtual',
        },
        {
            'therapist': 'Peter Pan',
            'client': 'Londyn Rivers',
            'start_time': datetime(year=2023, month=10, day=12, hour=14, minute=0),
            'end_time': datetime(year=2023, month=10, day=12, hour=14, minute=45),
            'app_type': 'Home',
        },
        {
            'therapist': 'Peter Pan',
            'client': 'Bear Peralta',
            'start_time': datetime(year=2023, month=10, day=12, hour=15, minute=0),
            'end_time': datetime(year=2023, month=10, day=12, hour=15, minute=45),
            'app_type': 'Home',
        },
        {
            'therapist': 'Sloan Hunter',
            'client': 'Malayah Hodges',
            'start_time': datetime(year=2023, month=10, day=12, hour=9, minute=0),
            'end_time': datetime(year=2023, month=10, day=12, hour=9, minute=45),
            'app_type': 'Home',
        },
        {
            'therapist': 'Sloan Hunter',
            'client': 'Alonzo Travis',
            'start_time': datetime(year=2023, month=10, day=12, hour=11, minute=0),
            'end_time': datetime(year=2023, month=10, day=12, hour=11, minute=45),
            'app_type': 'Home',
        },
        {
            'therapist': 'Sloan Hunter',
            'client': 'Mazikee Walter',
            'start_time': datetime(year=2023, month=10, day=12, hour=14, minute=0),
            'end_time': datetime(year=2023, month=10, day=12, hour=14, minute=45),
            'app_type': 'Home',
        },
        {
            'therapist': 'Mathew Patton',
            'client': 'Lochlan Tang',
            'start_time': datetime(year=2023, month=10, day=12, hour=9, minute=0),
            'end_time': datetime(year=2023, month=10, day=12, hour=9, minute=45),
            'app_type': 'Office',
        },
        {
            'therapist': 'Mathew Patton',
            'client': 'Belle Jennings',
            'start_time': datetime(year=2023, month=10, day=12, hour=10, minute=0),
            'end_time': datetime(year=2023, month=10, day=12, hour=10, minute=45),
            'app_type': 'Office',
        },
        {
            'therapist': 'Mathew Patton',
            'client': 'Corbin Young',
            'start_time': datetime(year=2023, month=10, day=12, hour=14, minute=0),
            'end_time': datetime(year=2023, month=10, day=12, hour=14, minute=45),
            'app_type': 'Office',
        },
        {
            'therapist': 'Mathew Patton',
            'client': 'Zoey Schneider',
            'start_time': datetime(year=2023, month=10, day=12, hour=15, minute=0),
            'end_time': datetime(year=2023, month=10, day=12, hour=15, minute=45),
            'app_type': 'Office',
        },
        {
            'therapist': 'Lorelei Norman',
            'client': 'Raymond Novak',
            'start_time': datetime(year=2023, month=10, day=12, hour=9, minute=0),
            'end_time': datetime(year=2023, month=10, day=12, hour=9, minute=45),
            'app_type': 'Remote',
        },
        {
            'therapist': 'Lorelei Norman',
            'client': 'Kaiya Beil',
            'start_time': datetime(year=2023, month=10, day=12, hour=10, minute=0),
            'end_time': datetime(year=2023, month=10, day=12, hour=10, minute=45),
            'app_type': 'Remote',
        },
        {
            'therapist': 'Lorelei Norman',
            'client': 'Ariel Fuller',
            'start_time': datetime(year=2023, month=10, day=12, hour=14, minute=0),
            'end_time': datetime(year=2023, month=10, day=12, hour=14, minute=45),
            'app_type': 'Remote',
        },
        {
            'therapist': 'Lorelei Norman',
            'client': 'Oakley Bean',
            'start_time': datetime(year=2023, month=10, day=12, hour=15, minute=0),
            'end_time': datetime(year=2023, month=10, day=12, hour=15, minute=45),
            'app_type': 'Remote',
        },
        {
            'therapist': 'Aziel Durham',
            'client': 'Mccoy Bass',
            'start_time': datetime(year=2023, month=10, day=12, hour=9, minute=0),
            'end_time': datetime(year=2023, month=10, day=12, hour=9, minute=45),
            'app_type': 'Home',
        },
        {
            'therapist': 'Aziel Durham',
            'client': 'Zahra O\'brien',
            'start_time': datetime(year=2023, month=10, day=12, hour=12, minute=0),
            'end_time': datetime(year=2023, month=10, day=12, hour=12, minute=45),
            'app_type': 'Home',
        },
        {
            'therapist': 'Aziel Durham',
            'client': 'Riley Salgado',
            'start_time': datetime(year=2023, month=10, day=12, hour=15, minute=0),
            'end_time': datetime(year=2023, month=10, day=12, hour=15, minute=45),
            'app_type': 'Home',
        },
        {
            'therapist': 'Tiffany Mueller',
            'client': 'Avalynn Daniels',
            'start_time': datetime(year=2023, month=10, day=12, hour=9, minute=0),
            'end_time': datetime(year=2023, month=10, day=12, hour=9, minute=45),
            'app_type': 'Office',
        },
        {
            'therapist': 'Tiffany Mueller',
            'client': 'Xander Fowler',
            'start_time': datetime(year=2023, month=10, day=12, hour=10, minute=0),
            'end_time': datetime(year=2023, month=10, day=12, hour=10, minute=45),
            'app_type': 'Office',
        },
        {
            'therapist': 'Tiffany Mueller',
            'client': 'Lennon Ortega',
            'start_time': datetime(year=2023, month=10, day=12, hour=14, minute=0),
            'end_time': datetime(year=2023, month=10, day=12, hour=14, minute=45),
            'app_type': 'Office',
        },
        {
            'therapist': 'Tiffany Mueller',
            'client': 'Kobe Welch',
            'start_time': datetime(year=2023, month=10, day=12, hour=15, minute=0),
            'end_time': datetime(year=2023, month=10, day=12, hour=15, minute=45),
            'app_type': 'Office',
        },
        {
            'therapist': 'Albert Berry',
            'client': 'Amira McBride',
            'start_time': datetime(year=2023, month=10, day=13, hour=9, minute=0),
            'end_time': datetime(year=2023, month=10, day=13, hour=9, minute=45),
            'app_type': 'Home',
        },
        {
            'therapist': 'Albert Berry',
            'client': 'Denver Charles',
            'start_time': datetime(year=2023, month=10, day=13, hour=11, minute=0),
            'end_time': datetime(year=2023, month=10, day=13, hour=11, minute=45),
            'app_type': 'Home',
        },
        {
            'therapist': 'Albert Berry',
            'client': 'Jenna Orr',
            'start_time': datetime(year=2023, month=10, day=13, hour=14, minute=0),
            'end_time': datetime(year=2023, month=10, day=13, hour=14, minute=45),
            'app_type': 'Home',
        },
        {
            'therapist': 'Annabelle Copeland',
            'client': 'Toby Day',
            'start_time': datetime(year=2023, month=10, day=13, hour=9, minute=0),
            'end_time': datetime(year=2023, month=10, day=13, hour=9, minute=45),
            'app_type': 'Office',
        },
        {
            'therapist': 'Annabelle Copeland',
            'client': 'Toby Day',
            'start_time': datetime(year=2023, month=10, day=13, hour=10, minute=0),
            'end_time': datetime(year=2023, month=10, day=12, hour=10, minute=45),
            'app_type': 'Office',
        },
        {
            'therapist': 'Annabelle Copeland',
            'client': 'Toby Day',
            'start_time': datetime(year=2023, month=10, day=13, hour=14, minute=0),
            'end_time': datetime(year=2023, month=10, day=13, hour=14, minute=45),
            'app_type': 'Office',
        }
    ]
}


def clean_name(name):
    return name.lower().replace(' ', '_')


def create_users(*args, **kwargs):
    for app in mock_data['Appointment']:
        try:
            a = Appointment(
                therapist=Therapist.objects.get(name=app['therapist']),
                client=Client.objects.get(name=app['client']),
                start_time=app['start_time'],
                end_time=app['end_time'],
                app_type=app['app_type']
            )
            a.save()
        except:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('guard', '0002_auto_20231011_1740'),
    ]

    operations = [
        migrations.RunPython(create_users),
    ]
